typography_spectrum: 0.12475302559323609
color:
  brandStrength: 0.7838568526785821
  lightness: 0.7697021849453449
  saturation: 0.8903614287264645
  rhythmicContrast: 0.22841692250221968
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
layout_spectrum: 0.48143338854424655
author:
  name: Marcus P
  email: marcus@marcusplatt.co.uk
  url: 'http://marcusplatt.co.uk/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e35effc-2d83-4c65-bd6f-3edcd4994bda.png
name: Bellamy VW
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8ca013cd-11d1-42cb-b9fa-0da5ac669d46.png
title: Bellamy the VW Campervan
description: Adventures in our T25 Campervan
